#-------------------------------------------------------------------------------
# Copyright (C) 2017 Create-Net / FBK.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Create-Net / FBK - initial API and implementation
#-------------------------------------------------------------------------------
language: node_js
node_js:
- '7'
sudo: required
addons:
  ssh_known_hosts: demo-fit.saclay.inria.fr
  apt:
    packages:
    - screen
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_2d87cfe52d6c_key -iv $encrypted_2d87cfe52d6c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv id_rsa_agile /tmp/id_rsa_agile
- mv ssh.sh /tmp/ssh.sh
- chmod 600 /tmp/id_rsa_agile
- eval "$(ssh-agent -s)"
- ssh-add /tmp/id_rsa_agile
- screen -d -m bash /tmp/ssh.sh

script:
  - npm test
